version: '3.8'
services:
  app:
    container_name: LoanProAPI
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - db_data:/app/db_data # Mount a volume to manage SQLite database file
    environment:
      - NODE_ENV=production
      - APP_PORT=3001
      # Database
      - DB_FILENAME=./db_data/db.sqlite3
      - DB_TEST_FILENAME=./db_data/db.test.sqlite3
      # API
      - API_VERSION=v1
      # Security
      - APP_SECRET=jfhhfj123
      # Random String Generator API
      - RANDOM_API=https://www.random.org
    networks:
      - app_network

  db:
    container_name: sqlite_db
    image: "sqlite"
    restart: unless-stopped
    volumes:
      - db_data:/data
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:

